[package]
name = "genetic_algo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-utils = "0.8.6"
rand = "0.8.4"

[profile.dev]
opt-level = 3
